import React from "react";
import Appbar from "../../Components/Appbar";
import Footer from "../../Components/Footer";

import "./css/companyprofile.css";
function Companyhistory() {

    return (
        <div>
            <div style={{display:"flex", flexDirection:"column"}}>
                <Appbar />
                <div className="location">
                    <p className="location_text">Home　{'>'}　<span className="location_text_dest">About IBJ</span></p>
                </div>
                <div className="first-container">
                    <p className="one">About Us</p>
                    <h1 className="two">Company History</h1>
                </div>
                <div className="hr" />
                <div style={{ margin: "10px 270px 0px 270px" }}>
                    <div style={{display:"flex"}}>
                        <div style={{backgroundColor:"#027bb3", width:"10px", marginRight:"15px"}}/>
                        <h2 style={{}}>A pioneer in “Kon-Katsu (marriage-hunting)” services provided online and in real life.</h2>
                    </div>
                    <p style={{marginLeft:"25px"}}>As a pioneering company that started a new online service (marriage-hunting) in Japan, we continue to offer new ideas through offline services (real-life marriage-hunting) as well.</p>
                </div>
                <table className="table">
                    <tr>
                        <th>2006</th>
                        <td>
                            <ul style={{ lineHeight: "1.3" }} className="bullet-list">
                                <li>Became independent from Yahoo Japan Corporation and established IBJ, Inc.​</li><br/>
                                <li>Since many members did not progress to forming a relationship, launched Japan Marriage Consulting Federation business which is operated by face-to-face halls and which places a premium on success.​</li>
                            </ul>
                        </td>
                    </tr>
                    <tr>
                        <th>2008</th>
                        <td>
                            <ul style={{ lineHeight: "1.2" }} className="bullet-list">
                                <li>In order to boost attractiveness of the Japan Marriage Consulting Federation, launched marriage consulting agency lounge business at directly managed hall.​​</li>
                            </ul>
                        </td>
                    </tr>
                    <tr>
                        <th>2015</th>
                        <td>
                            <ul style={{ lineHeight: "1.2" }} className="bullet-list">
                                <li>​​Listed on the First Section of the Tokyo Stock Exchange.​</li>
                            </ul>
                        </td>
                    </tr>
                    <tr>
                        <th>2016</th>
                        <td>
                            <ul style={{ lineHeight: "1.2" }} className="bullet-list">
                                <li>​By utilizing marriage-hunting membership base and using supporting know-how, became a comprehensive life design company.​​</li>
                            </ul>
                        </td>
                    </tr>
                    <tr>
                        <th>2019</th>
                        <td>
                            <ul style={{ lineHeight: "1.2" }} className="bullet-list">
                                <li>​​Acquired two companies（K Village Tokyo Co.,Ltd and Sunmarie Co.,Ltd )</li>
                            </ul>
                        </td>
                    </tr>
                    <tr>
                        <th>2020</th>
                        <td>
                            <ul style={{ lineHeight: "1.2" }} className="bullet-list">
                                <li>​Acquired one company（ZWEI Co.,Ltd）​</li>
                            </ul>
                        </td>
                    </tr>
                    <tr>
                        <th>2021</th>
                        <td>
                            <ul style={{ lineHeight: "1.2" }} className="bullet-list">
                                <li>Of the couples married in Japan (about 514,242), 2.0% (10,402) were generated by IBJ.​​</li><br />
                                <li>Concluded business alliance with 14 local banks.​​</li>
                            </ul>
                        </td>
                    </tr>
                    <tr>
                        <th>2022</th>
                        <td>
                            <ul style={{ lineHeight: "1.2" }} className="bullet-list">
                                <li>Transitioned to the Tokyo Stock Exchange Prime Market​​</li><br />
                                <li>Partnerships with regional financial institutions, 16th case​​</li><br />
                                <li>11,921 marriages created (2.3% of all marriages in Japan)​</li>
                            </ul>
                        </td>
                    </tr>
                    <tr>
                        <th>2023</th>
                        <td>
                            <ul style={{ lineHeight: "1.3" }} className="bullet-list">
                                <li>​Number of marriage agencies exceeded 4,000 companies​</li><br/>
                                <li>​​The number of arranged marriages meetings in September exceeded 60,000, the highest for a single month</li><br/>
                                <li>​​12,527 marriages created (2.6% of all marriages in Japan)</li><br/>
                                <li>​Capital and business alliance with O-Net Inc.</li>
                            </ul>
                        </td>
                    </tr>
                </table>
            </div>
        <Footer/>
        </div>
  );
}

export default Companyhistory;
